---
title: "UncertainOrd"
author: "Andrew Hoegh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Spider Data

As an example, the spider data set is used for ordination. First the abundance data is converted to presence/absence.

```{r}
#library(mvabund)
#library(knitr)
#library(dplyr)
#install_github('andyhoegh/UncertainOrd')
#library(UncertainOrd)
#library(tidyr)
#library(ggplot2)
data(spider, package='mvabund')
spider.matrix <- matrix(as.numeric(spider$abund > 0), nrow = 28, ncol = 12)
knitr::kable(spider.matrix, col.names = colnames(spider$abund))
```

## Ordination Model

The latent factor model is used for ordination.
```{r}
ord <- UncertainOrd::ordinate_probit(500, spider.matrix)
```


## Data Visualization

Using the output from the model above, we can create ordination figures.
```{r}
UncertainOrd::CredibleViz(ord$z.samples[,,1], ord$z.samples[,,2], type = 'points')
UncertainOrd::CredibleViz(ord$z.samples[,,1], ord$z.samples[,,2], type = 'scatter', items = c(1,10,16))
UncertainOrd::CredibleViz(ord$z.samples[,,1], ord$z.samples[,,2], type = 'circles', items = c(1,10,16))
UncertainOrd::CredibleViz(ord$z.samples[,,1], ord$z.samples[,,2], type = 'density', items = c(1,10,16))

```

